spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=master;encrypt = false
    username: sa
    password: Fsoft123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      show-sql: true
      ddl-auto: update
